#one line one sensor
#NO space is supported
#name,vendor,version,handle,type,maxRange,resolution,power,minDelay,fifoReservedEventCount,fifoMaxEventCount,stringType,requiredPermission,maxDelay,flags
MRVL Accelerometer,BOSCH,1,MRVL_ACCELERATION_HANDLE,SENSOR_TYPE_ACCELEROMETER,78.4f,1.0f,0.5f,10000,0,800,SENSOR_FLAG_CONTINUOUS_MODE

MRVL WakeUp Accelerometer,BOSCH,1,MRVL_ACCELERATION_WAKEUP_HANDLE,SENSOR_TYPE_ACCELEROMETER,78.4f,1.0f,0.5f,10000,0,800,SENSOR_FLAG_WAKE_UP

MRVL Light,AVAGO,1,MRVL_LIGHT_HANDLE,SENSOR_TYPE_LIGHT,2000.0f,1.0f,0.5f,50000,0,600,SENSOR_FLAG_ON_CHANGE_MODE

MRVL WakeUp Light,AVAGO,1,MRVL_LIGHT_WAKEUP_HANDLE,SENSOR_TYPE_LIGHT,2000.0f,1.0f,0.5f,50000,0,600,SENSOR_FLAG_WAKE_UP

MRVL Proximity,AVAGO,1,MRVL_PROXIMITY_HANDLE,SENSOR_TYPE_PROXIMITY,2000.0f,1.0f,0.5f,50000,0,600,SENSOR_FLAG_ON_CHANGE_MODE

#MRVL Gyroscope,ST,1,MRVL_GYROSCOPE_HANDLE,SENSOR_TYPE_GYROSCOPE,2000.0f,1.0f,0.5f,5000,0,600

#MRVL Magnetic Field,ST,1,MRVL_MAGNETIC_FIELD_HANDLE,SENSOR_TYPE_GEOMAGNETIC_FIELD,0.0012f,1.0f,0.5f,20000,0,600

#MRVL Barometer,ST,1,MRVL_BAROMETER_HANDLE,SENSOR_TYPE_PRESSURE,1260.0f,1.0f,0.025f,40000,0,750

#MRVL temperature,ST,1,MRVL_AMBIENT_TEMPERATURE_HANDLE,SENSOR_TYPE_AMBIENT_TEMPERATURE,85.0f,0.002f,0.030f,40000,0,800

MRVL Step Detector,ST,1,MRVL_STEP_DETECTOR_HANDLE,SENSOR_TYPE_STEP_DETECTOR,100.0f,1.0f,1.1f,200000,0,1000,SENSOR_FLAG_ONE_SHOT_MODE

MRVL WakeUp Step Detector,ST,1,MRVL_STEP_DETECTOR_WAKEUP_HANDLE,SENSOR_TYPE_STEP_DETECTOR,100.0f,1.0f,1.1f,200000,0,1000,SENSOR_FLAG_WAKE_UP

MRVL Step Counter,ST,1,MRVL_STEP_COUNTER_HANDLE,SENSOR_TYPE_STEP_COUNTER,100.0f,1.0f,1.1f,200000,0,700,SENSOR_FLAG_ON_CHANGE_MODE

MRVL WakeUp Step Counter,ST,1,MRVL_STEP_COUNTER_WAKEUP_HANDLE,SENSOR_TYPE_STEP_COUNTER,100.0f,1.0f,1.1f,200000,0,700,SENSOR_FLAG_WAKE_UP

MRVL Significant Motion,ST,1,MRVL_SIGNIFICANT_MOTION_HANDLE,SENSOR_TYPE_SIGNIFICANT_MOTION,100.0f,1.0f,1.1f,0,0,0,SENSOR_FLAG_ONE_SHOT_MODE

MRVL Tilt Detector,ST,1,MRVL_TILT_HANDLE,SENSOR_TYPE_TILT_DETECTOR,100.0f,1.0f,1.1f,0,0,0,SENSOR_FLAG_ONE_SHOT_MODE

#MRVL Uncalibrated Gyroscope,Marvell,1,MRVL_UNCALIBRATED_GYROSCOPE_HANDLE,SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,2000.0f,1.0f,0.5f,10000,0,600

#MRVL Uncalibrated Magnetic Field, Marvell ,1,MRVL_UNCALIBRATED_MAGNETIC_FIELD_HANDLE,SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,0.0012f,1.0f,0.5f,20000,0,600

#MRVL Orientation,Marvell,1,MRVL_ORIENTATION_HANDLE,SENSOR_TYPE_ORIENTATION,360.0f,1.0f,9.7f,10000,0,0

#MRVL Rotation Vector,Marvell,1,MRVL_ROTATION_VECTOR_HANDLE,SENSOR_TYPE_ROTATION_VECTOR,10240.0f,1.0f,0.5f,10000,0,0

#MRVL Linear Acceleration, Marvell,1,MRVL_LINEAR_ACCEL_HANDLE,SENSOR_TYPE_LINEAR_ACCELERATION,10240.0f,1.0f,0.5f,10000,0,0

#MRVL Gravity,Marvell,1,MRVL_GRAVITY_HANDLE,SENSOR_TYPE_GRAVITY,10240.0f,1.0f,0.5f,10000,0,0

#MRVL Game Rotation Vector, Marvell,1,MRVL_GAME_ROTATION_VECTOR_HANDLE,SENSOR_TYPE_GAME_ROTATION_VECTOR,10240.0f,1.0f,0.5f,10000,0,0

#MRVL Geo Rotation Vector,Marvell,1,MRVL_GEOMAGNETIC_ROTATION_VECTOR_HANDLE,SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,10240.0f,1.0f,0.5f,10000,0,0

