#no space allowed at the beginning of line
#early suspend will follow the sequence and late resume vice versa
#you should specify path which contains control and runtime_status
#rohm touch
/sys/bus/i2c/devices/4-0048/power

#lcd
/sys/devices/platform/soc.1/d4200000.axi/fbbase.2/power
/sys/devices/platform/soc.1/d4200000.axi/d427f000.vdma/power
/sys/devices/platform/soc.1/d4200000.axi/d420b000.disp/power
